language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-madlib-module' ]; then cd .. && eval "mv $currentfolder generator-madlib-module" && cd generator-madlib-module; fi

